#!/bin/bash

source ./regression_helpers

VOLNAME="vol";
$GLUSTERFSDIR/gluster volume create $VOLNAME transport tcp,rdma $(hostname):$EXPORT_DIR/$global_bug_id/export1 2>/dev/null 1>/dev/null
exit $?;


