#!/bin/bash

source ./regression_helpers

$GLUSTERFSDIR/gluster volume create $global_bug_id $(hostname):$EXPORT_DIR/$global_bug_id/export1 2>/dev/null 1>/dev/null;

$GLUSTERFSDIR/gluster --mode=script volume start $global_bug_id 2>/dev/null 1>/dev/null;

$GLUSTERFSDIR/gluster volume start $global_bug_id | grep "alreadystarted"

if [ "$?" -eq "0" ]; then
   RET="1";
else
   RET="0";
fi

exit $RET;



