#!/bin/bash

source ./regression_helpers

VOLNAME="vol_2063";

$GLUSTERFSDIR/gluster volume create $VOLNAME replica 2 $(hostname):$EXPORT_DIR/$global_bug_id/export1 $(hostname):$EXPORT_DIR/$global_bug_id/export2 2>/dev/null 1>/dev/null;

$GLUSTERFSDIR/gluster volume start $VOLNAME 2>/dev/null 1>/dev/null;

$GLUSTERFSDIR/gluster volume set $VOLNAME performance.stat-prefetch on 2>/dev/null 1>/dev/null;

sleep 10;

mount_glusterfs $VOLNAME;
sleep 5;

mount_nfs $VOLNAME;
sleep 10;

for i in {1..10000};
do
    mkdir -p $FUSE_MOUNT/$i;
    for j in {1..100};
    do
        mkdir $FUSE_MOUNT/$i/$j && touch $FUSE_MOUNT/$i/$j/$j.file;
    done;
done;

ls -lR $FUSE_MOUNT/* 2>/dev/null 1>/dev/null & 
RET=`rm -rf $NFS_MOUNT/* | grep "Circular" | wc -l`;

wait;

exit $RET;